language: node_js
node_js: node
addons:
  firefox: latest-esr
  apt:
    packages:
      - dbus-x11
      - xvfb
before_script:
  - 'export DISPLAY='':99.0'''
  - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'
  - npm i
dist: xenial
services:
  - xvfb
