language: node_js
node_js: node
sudo: required
addons:
  firefox: "latest-esr"
  # Install D-Bus here
  apt:
    packages:
      - "dbus-x11"
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
